### ISSUE TITLE
Content Security Policy - blocked "unsafe eval" and "unsafe inline"

### ISSUE THREAD

**Issue by dbluhm** [byuweb/byu-theme-components#151]
# One-Line Summary
CSP blocks the use of unsafe inline scripts and the use of eval or similar functions in javascript.

# Websites Affected
We haven't pushed the theme to an externally visible location yet but if necessary we can probably get you something to look at.

# Issue Type

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [X] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [X] A request for a new feature/enhancement?

# Browsers Affected

## Desktop Browsers
**_Haven't tested with any other browsers but may be present._**

- [X] Google Chrome
- [X] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [X] Custom Site
- [ ] Don't Know

# Detailed Description

Content Security Policy will block parts of the scripts used by the BYU theme components, resulting in obvious issues in styling and rendering of some content period.

The error as reported in the JS console on google chrome:

![image](https://cloud.githubusercontent.com/assets/22032832/25052336/91a61fea-210e-11e7-9b7a-ae36c0f021c4.png)

How it renders the page:

![chrome_render_example](https://cloud.githubusercontent.com/assets/22032832/25052636/14cbb302-2110-11e7-9589-3468f0badc9b.png)

Firefox:

![image](https://cloud.githubusercontent.com/assets/22032832/25052392/d51cd76e-210e-11e7-95f1-e41421732621.png)

Render on Firefox:
![screenshot from 2017-04-14 12-45-48](https://cloud.githubusercontent.com/assets/22032832/25052702/6058876e-2110-11e7-9030-5f60971e9df7.png)

To reproduce, adding the header "Content-Security-Policy: script-src 'self' *; style-src 'self' 'unsafe-inline' *;" seems sufficient.

The original site (for reference; byu-theme is not yet applied in production) can be found [here](https://marylou.byu.edu).

**Comment by ThatJoeMoore** [comment]
@dbluhm I've pushed up a potential fix for you to test.  If you change the `latest` part of your path to `experimental/remove-search-eval`, you can test the change. (so, the import should look something like this: `<script async src="https://cdn.byu.edu/byu-theme-components/experimental/remove-search-eval/byu-theme-components.js">`)

**Comment by dbluhm** [comment]
Sorry for leaving you hanging on this for so long. For some reason I never received an email with your comment. At any rate, there still appear to be issues.
![screenshot from 2017-05-05 10-38-28](https://cloud.githubusercontent.com/assets/22032832/25755177/207fc1aa-317f-11e7-8870-67ea5a61aa7a.png)

Clearly this isn't complaining specifically about the use of eval but, again, adding the 'unsafe-eval' directive to the CSP header removes these errors.
It may be a usage of `new function("...")` or something similar.

Let me know if you need any more information. Thanks for your work.

**Comment by ThatJoeMoore** [comment]
Ahh, yeah.  I was just searching the main component scripts for evals, so I missed a `new Function()` call that we're making.  We're using it in our bootstrap script (the one you load when including byu-theme-components.js) in order to detect browser support for ES6, so that we can load the proper code bundle.

@Gi60s @kebowdog @katrialesser What do you think of, instead of feature-detecting ES6, always loading the `components-compat` bundle if the browser doesn't natively support the Web Component specs?  I mean, IE11 is the only non-ES6 browser that we support, so theoretically we could just check and see if the browser is IE, but I prefer to avoid that kind of user-agent sniffing.

**Comment by dbluhm** [comment]
@ThatJoeMoore how are things coming on this?

**Comment by ThatJoeMoore** [comment]
I'm actually working on a solution right now. I'll have something to test shortly, and then it should roll out later this week.

**Comment by ThatJoeMoore** [comment]
@dbluhm I believe I've got a solution. I've tested it on a server sending CSP headers, and it looks like everything is happy.  If you switch to loading your JS from this URL, you can test the fix:

`https://cdn.byu.edu/byu-theme-components/experimental/issue-151-csp-issues/byu-theme-components.js`

**Comment by dbluhm** [comment]
That seems to have taken care of it! Thanks for your help.

**Comment by ThatJoeMoore** [comment]
Where are you hitting the inline JS? AFAIK, there shouldn't be any of that.

As for the inline styling, we won't be able to get around that. It's simply just part of using the Shadow DOM specification. The spec designers have not, at this time, added good support for referencing external stylesheets within Shadow DOM; AFIAK, they've only documented the use of inline styles.  Even if external styles are supported by the spec, though, they are not supported by the polyfills that we are using to support IE/Edge and Firefox.  In order to emulate the styling rules of Shadow DOM, the polyfills have to be able to insert inline CSS.

**Comment by ThatJoeMoore** [comment]
For my own future reference, here's how I emulated the CSP headers while developing locally:

Running `gulp serve`, I also spun up GoogleChrome/simplehttp2server with the following config:

```
{
  "headers": [
    {
      "source": "/**.html",
      "headers": [
        {
          "key": "Content-Security-Policy",
          "value": "script-src 'self' *; style-src 'self' 'unsafe-inline' *;"
        }
      ]
    }
  ]
}

```

**Comment by dbluhm** [comment]
My bad on the inline javascript comment, that was actually something being included from some old code on our site >.< We're still in the process of getting things cleaned up to be CSP safe, too.

As far as inline styling, if you can figure anything out about that, that would be great.
